site_name: Brandy Box
site_description: Development documentation
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Backend: backend/overview.md
  - Client:
    - Overview: client/overview.md
    - Tauri client: client/tauri.md
    - Troubleshooting: client/troubleshooting.md
  - License: license.md
